-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-03-13 17:25:05 CLST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE alternativas (
    correccion_alternativa   CHAR(1),
    descripcion_alternativa  VARCHAR2(100 CHAR),
    id_alternativa           INTEGER NOT NULL,
    puntaje_alternativa      INTEGER,
    preguntas_id_pregunta    INTEGER NOT NULL
);

ALTER TABLE alternativas ADD CONSTRAINT alternativas_pk PRIMARY KEY ( id_alternativa );

CREATE TABLE alumno (
    id_alumno       INTEGER NOT NULL,
    nombre_alumno   VARCHAR2(100 CHAR) NOT NULL,
    curso_id_curso  INTEGER NOT NULL,
    test_id_test    INTEGER
);

ALTER TABLE alumno ADD CONSTRAINT alumno_pk PRIMARY KEY ( id_alumno );

CREATE TABLE curso (
    id_curso    INTEGER NOT NULL,
    tipo_curso  VARCHAR2(20 CHAR)
);

ALTER TABLE curso ADD CONSTRAINT curso_pk PRIMARY KEY ( id_curso );

CREATE TABLE preguntas (
    id_pregunta         INTEGER NOT NULL,
    enunciado_pregunta  VARCHAR2(100 CHAR),
    puntaje_pregunta    FLOAT(2),
    test_id_test        INTEGER NOT NULL
);

ALTER TABLE preguntas ADD CONSTRAINT preguntas_pk PRIMARY KEY ( id_pregunta );

CREATE TABLE respuestas (
    id_respuestas                INTEGER NOT NULL,
    respuesta                    CHAR(1) NOT NULL,
    alternativas_id_alternativa  INTEGER,
    alumno_id_alumno             INTEGER NOT NULL
);

ALTER TABLE respuestas ADD CONSTRAINT respuestas_pk PRIMARY KEY ( id_respuestas );

CREATE TABLE evaluacion (
    id_test        INTEGER NOT NULL,
    nombre_test    VARCHAR2(20 CHAR),
    descrip_test   VARCHAR2(100 CHAR),
    programa_test  VARCHAR2(50 CHAR),
    unidad_test    VARCHAR2(10 CHAR),
    autor_test     VARCHAR2(50 CHAR),
    fecha_test     DATE
);

ALTER TABLE test ADD CONSTRAINT test_pk PRIMARY KEY ( id_test );

ALTER TABLE alternativas
    ADD CONSTRAINT alternativas_preguntas_fk FOREIGN KEY ( preguntas_id_pregunta )
        REFERENCES preguntas ( id_pregunta );

ALTER TABLE alumno
    ADD CONSTRAINT alumno_curso_fk FOREIGN KEY ( curso_id_curso )
        REFERENCES curso ( id_curso );

ALTER TABLE alumno
    ADD CONSTRAINT alumno_test_fk FOREIGN KEY ( test_id_test )
        REFERENCES test ( id_test );

ALTER TABLE preguntas
    ADD CONSTRAINT preguntas_test_fk FOREIGN KEY ( test_id_test )
        REFERENCES test ( id_test );

ALTER TABLE respuestas
    ADD CONSTRAINT respuestas_alternativas_fk FOREIGN KEY ( alternativas_id_alternativa )
        REFERENCES alternativas ( id_alternativa );

ALTER TABLE respuestas
    ADD CONSTRAINT respuestas_alumno_fk FOREIGN KEY ( alumno_id_alumno )
        REFERENCES alumno ( id_alumno );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
